version: "3.8"

services:
  file-service:
    restart: always
    depends_on:
      - minio
    image: file-service
    container_name: file-service
    build: ./
    command: sh -c "./wait-for-minio.sh minio:9000 && ./file-service"
    volumes:
      - ./configs:/root/configs
    env_file:
      - .env
    ports:
      - "8081:8081"

  minio:
    restart: always
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
    volumes:
      - minio_data:/data
    command: server /data/
    env_file:
      - .env
    ports:
      - "9000:9000"

volumes:
  minio_data:
