version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
    volumes:
      - data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioAccessKey
      MINIO_SECRET_KEY: minioSecretKey 
    command: server /data/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data:
